version: '3.7'
services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: myworkoutapp_client
    ports:
    - 3000:3000
    volumes:
    - ./:/opt/Myapp/workoutapp
    - /opt/Myapp/workoutapp/node_modules
    environment:
      NODE_ENV: development      
      CHOKIDAR_USEPOLLING: 1